
[font.bold]
family = "Iosevka Nerd Font Mono"

[font.bold_italic]
family = "Iosevka Nerd Font Mono"

[font.italic]
family = "Iosevka Nerd Font Mono"

[font.normal]
family = "Iosevka Nerd Font Mono"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[general]
import = ["/home/adam/.config/alacritty/local.toml", "/home/adam/.config/alacritty/nightfox_alacritty.toml"]

[window]
startup_mode = "Fullscreen"

[keyboard]
