[colors.bright]
black = "0x484848"
blue = "0x8cb6ff"
cyan = "0x52bdff"
green = "0x46c880"
magenta = "0xc8a5ff"
red = "0xf16da6"
white = "0xe4e4e5"
yellow = "0x2dc7c4"

[[colors.indexed_colors]]
color = "0x3ddbd9"
index = 16

[[colors.indexed_colors]]
color = "0xff7eb6"
index = 17

[colors.normal]
black = "0x282828"
blue = "0x78a9ff"
cyan = "0x33b1ff"
green = "0x25be6a"
magenta = "0xbe95ff"
red = "0xee5396"
white = "0xdfdfe0"
yellow = "0x08bdba"

[colors.primary]
background = "0x161616"
foreground = "0xf2f4f8"
